### ISSUE TITLE
Does not work on Windows 😍 

### ISSUE THREAD

**Issue by shift-d** [udayvir-singh/tangerine.nvim#10]
Basically what's wrong: it seems that Git cannot properly load symlinks.
So tangerine.fennel.latest becomes an invalid lua file with symlinked path as content.

**Comment by udayvir-singh** [comment]
@shift-d 

I don't use windows neither do I plan to use it. So I never got a chance to test it on windows and to be honest I don't even want to support windows at all.

You can create a fork that supports windows but I wouldn't be able to help since I don't know how to use windows.
