### ISSUE TITLE
The 'globals' option should add on to the default value, not replace it

### ISSUE THREAD

**Issue by oblitzitate** [udayvir-singh/tangerine.nvim#11]
When setting up the `globals` option for compiling a dir, I have to first create the `vim.tbl_keys(_G)` table before I can add in new global values like `awesome` (for AwesomeWM). Otherwise, if I just add the new global values, it will cause a compilation error where it doesn't recognize functions like `pcall` and `require`. Unless I'm doing something incorrectly.

My suggestion is that the custom values should add on to the default values instead of replace it. 

Maybe add a `clear_default_globals` option if you truly wanted to replace the default values.

Maybe even rename `globals` to `custom_globals` to be more precise,

**Comment by oblitzitate** [comment]
This is my current workaround:

```lua
local awesome_dir = os.getenv("HOME") .. "/.config/awesome"
_G.tangerine.api.compile.dir(
  awesome_dir .. "/fnl",
  awesome_dir .. "/lua",
  { globals = (function()
    local new = vim.tbl_keys(_G)
    table.insert(new, "awesome")
    table.insert(new, "root")
    table.insert(new, "modkey")
    table.insert(new, "RC")
    return new
  end)() }
)
```

**Comment by udayvir-singh** [comment]
@oblitzitate 

Adding another option like `clear_default_globals` would complicate the internal code for no reason. Just use `vim.list_extend` for adding globals:
```lua
{
  globals = vim.list_extend(vim.tbl_keys(_G), {"awesome", "root", "modkey", "RC"})
}
```
