### ISSUE TITLE
Tried setting packer as you showed in the default example, and i have an error

### ISSUE THREAD

**Issue by hrqmonteiro** [udayvir-singh/tangerine.nvim#14]
![Screenshot from 2022-08-08 18-22-40](https://user-images.githubusercontent.com/17055027/183517024-8baf2fea-7817-40db-b8a5-0be0531d469b.png)

My tangerine file:

![Screenshot from 2022-08-08 18-22-53](https://user-images.githubusercontent.com/17055027/183517057-08bb6cdc-88c7-4685-84d1-ad098e73dfeb.png)

**Comment by udayvir-singh** [comment]
@h

**Comment by udayvir-singh** [comment]
@hrqmonteiro

That error was caused because `use` was not in current scope. It can simply be fixed by:
```fennel
(local packer (require :packer))

(packer.startup (lambda [use]
  (use :udayvir-singh/tangerine.nvim)))
```

Thanks for pointing out this typo.
