### ISSUE TITLE
Silence FnlFile

### ISSUE THREAD

**Issue by theocodes** [udayvir-singh/tangerine.nvim#15]
Hi there 👋 

Firstly, thanks for creating this project! I've tried a few of the options out there and found the experience with tangerine to be superior in many ways!

I wanted to ask if there's currently a way to silence the output when running 'FnlFile ..'?

I find that i don't really need it and it gets in the way of my workflow of auto evaluating and running packer sync when my plugins file is changed.

I'm more than happy to contribute with this change if needed, but wanted to get your input first.

What I was thinking was adding a 'verbose' option to 'eval', similar to 'compile'. What do you think?

Thanks!

**Comment by udayvir-singh** [comment]
@theocodes

You can just add `nil` at the end of your files like I do most of times and this will suppress the output. for example:
```
(local M {})

(lambda M.foo []
  (print :hello))

:return M

nil
```

Just remember to remove `nil` afterwards.

**Comment by theocodes** [comment]
Ah great! I think that definitely works for my specific use-case 👍

Thanks @udayvir-singh
