### ISSUE TITLE
Fennel to lua does not compile to `target`

### ISSUE THREAD

**Issue by justAlex0** [udayvir-singh/tangerine.nvim#21]
## Expected Behavior
Compiled fennel to lua files go to `target`

## Current Behavior
Fennel compiles into `source` 

## 

``` lua
-- init.lua
local function bootstrap(user, repo)
    local fn = vim.fn
    local install_path = fn.stdpath("data") .. "/lazy/" .. repo
    if (fn.empty(fn.glob(install_path)) > 0) then
        fn.system({"git", "clone", "--depth", "1", ("https://github.com/" .. user .. "/" .. repo.. ".git"), install_path})
    end
    vim.opt.runtimepath:prepend(install_path)
end

bootstrap("folke", "lazy.nvim")
bootstrap("udayvir-singh", "tangerine.nvim")

local config = vim.fn.stdpath [[config]]
require "tangerine".setup({
    source  = config .. "/fnl",
    target  = vim.fn.stdpath [[cache]] .. "/lua",
    compiler = {
        hooks = {"onsave", "oninit"},
    },
})
require("init")
```

Though if there's `init.fnl` it alone compiles into `target`.

**Comment by udayvir-singh** [comment]
@justAlex0 I can't seem to replicate the issue, can you give me some more info about:
1. Did you try to run `:FnlClean`
2. Your OS
3. `tree` command output on both `source` and `target` dirs.
```
$ tree ~/.config/nvim/fnl
$ tree ~/.cache/nvim/lua
```

**Comment by justAlex0** [comment]
`:FnlClean` does not clean compiled lua files in either `.cache` or `.config`. I clean them externally through termial
1. Arch
2. 
```
Didn't past the full output because there're a lot of files but every .fnl has its .lua
└── .config
   └── nvim
      ├── fnl
      │  ├── init.fnl
      │  ├── init.lua
      │  ├── macros.fnl
      │  ├── opts.fnl
      │  ├── opts.lua
      │  ├── plugins
      │  │  ├── *
      │  ├── statuscolumn.fnl
      │  └── statuscolumn.lua
      ├── ftplugin
      │  ├── .fennel.fnl
      │  ├── fennel.lua
      │  └── sh.lua
      ├── init.fnl    // with just (set vim.opt.colorcolumn "80") to see if works
      └── init.lua
```
```
└── .cache
   └── nvim
      └── lua
         └── tangerine_vimrc.lua  // and it works
```

**Comment by udayvir-singh** [comment]
You aren't supposed to have two `init.fnl` files - `nvim/init.fnl` and `nvim/fnl/init.fnl`, maybe they are causing a loopback. I got this error when I tried to replicate your config:

```
Error detected while processing /home/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ./init.lua:20: loop or previous error loading module 'in
it'
stack traceback:
        [C]: in function 'require'
        ./init.lua:20: in main chunk
        [C]: in function 'require'
        /home/user/.config/nvim/init.lua:20: in main chunk
```

Try to remove `nvim/fnl/init.fnl` or set it as your default vimrc:
```lua
require "tangerine".setup {
    vimrc = config .. "/fnl/init.fnl",
}
```

**Comment by udayvir-singh** [comment]
Other than that, your config works like normal on my machine and on testing docker container.

> I use arch btw

**Comment by udayvir-singh** [comment]
Just read your dotfiles and only problem that I could find was you trying to require init.fnl manually. You don't have to do that with tangerine, it will require it for you. So remove this line:
```diff
 -- init.lua

 require "tangerine".setup({
+    vimrc    = config .. "/fnl/init.fnl",
     source   = config .. "/fnl",
     target   = vim.fn.stdpath [[cache]] .. "/lua",
     compiler = {
         hooks = {"onsave", "oninit"},
     },
 })
-require "init"

```

**Comment by justAlex0** [comment]
> You aren't supposed to have two init.fnl files

There's no loopback even if i take `require("init")` from `init.lua` and put as `(require :init)` inside `init.fnl`. 
But even if i delete `init.fnl`, tangerine just cleans `tangerine_vimrc.lua` inside `target`.

#
Now considering your snippet, `/fnl/init.fnl` compiles into `target` instead of the default `init.fnl`. Everything else is the same.

Also neovim and all the plugins and configs work as intended.

**Comment by udayvir-singh** [comment]
@justAlex0 I really am out of ideas for what might be happening. What version of neovim are you using?

**Comment by justAlex0** [comment]
NVIM v0.8.2

**Comment by justAlex0** [comment]
I guess i should play a bit with tangerine source, if it just something cursed on my end

**Comment by udayvir-singh** [comment]
I am using the same version on same OS and can't seem to replicate this behavior.

Can you clean you nvim config for a while and only add the following files:
```yaml
- init.fnl
- plugin:
    - 0-tangerine.fnl
- fnl:
    - hello.fnl
```

```lua
-- 0-tangerine.fnl

local pack = "tangerine"

local function bootstrap(url, ref)
	local name = url:gsub(".*/", "")
	local path = vim.fn.stdpath [[data]] .. "/site/pack/".. pack .. "/start/" .. name

	if vim.fn.isdirectory(path) == 0 then
		print(name .. ": installing in data dir...")

		vim.fn.system {"git", "clone", url, path}
		if ref then
			vim.fn.system {"git", "-C", path, "checkout", ref}
		end

		vim.cmd [[redraw]]
		print(name .. ": finished installing")
	end
end

bootstrap("https://github.com/udayvir-singh/tangerine.nvim", "v2.3")

require "tangerine".setup {
    compiler = { hooks = {"oninit"} }
}
```

```fennel
;; init.fnl

(require :hello)
```

```fennel
;; hello.fnl

(print "HELLO WORLD!")
```

And then see what happens

**Comment by justAlex0** [comment]
Added. This still do not follow `target` 
```
└── nvim
   ├── fnl
   │  ├── hello.fnl
   │  └── hello.lua
   ├── init.fnl
   ├── lua
   │  └── tangerine_vimrc.lua
   └── plugin
      └── 0-tangerine.lua
```

**Comment by udayvir-singh** [comment]
Then there is nothing that I can do at this point. You should keep on using hotpot than to get messy with tangerine's internals.
