### ISSUE TITLE
Windows support (round two)

### ISSUE THREAD

**Issue by Sharparam** [udayvir-singh/tangerine.nvim#25]
In issue #10 there was an issue with symbolic links in Git on windows, but this now works since some time back.

However, there's a different issue that now appears in tangerine:

Tangerine hardcodes `/` (forward slash) as the path separator, including in places where it uses `match` and friends to extract different parts of paths. This of course breaks on Windows which uses a `\` (backslash).

It feels like it should be a simple enough fix, since Windows does support using `/` as a separator it would probably be possible to just add support for converting automatically and also detecting `\` in addition to `/` in places such as the `shortname` function and `fs.write`.

The current OS is available in `jit.os` so this special code could also be guarded so it does not run at all unless the user is on Windows, to prevent any possible issues that could occur by trying to support `\` on Linux where it's not necessary.

I could look into making this work if a PR is welcome @udayvir-singh?

**Comment by udayvir-singh** [comment]
@Sharparam Ok, I will merge your PR as long as it doesn't disturb any parts of the API.

**Comment by bandithedoge** [comment]
@Sharparam Are you still interested in fixing this issue?

**Comment by Sharparam** [comment]
Yes, sorry. Unless someone else is also expressing recent interest. Was caught up with work and then vacation started so I haven't been on the Windows system I use (at work).
