### ISSUE TITLE
[Bug] inconsistent `onsave` hook

### ISSUE THREAD

**Issue by alexmozaidze** [udayvir-singh/tangerine.nvim#28]
Whenever I go to change my configs under `~/.config/nvim/fnl/` or even `~/.config/nvim/init.fnl`, it *sometimes* doesn't compile after changes. After re-opening the file it starts to work..? I am unsure of how this bug occurs or how to reproduce it.

I looked into the source code and checked with `au BufWritePost`, the paths seem normal.

**Comment by udayvir-singh** [comment]
@alexmozaidze can you set `compiler.verbose` in tangerine's setup to `true` and then restart neovim and open a file in `compiler.source` directory and execute `:w`, here tangerine should open a window with the files being compiled. Also show me your setup function.

**Comment by udayvir-singh** [comment]
@alexmozaidze I just added a commit that escapes autocmd patterns like `*` `,` `\` from the file paths, try updating tangerine and tell me if it fixed the issue.

**Comment by alexmozaidze** [comment]
```lua
require "tangerine".setup {
  compiler = {
    hooks = { "oninit", "onsave" },
    verbose = true,
  }
}
```
The commit does not fix the issue. I was able to find a way to reproduce it, though:
1. open NeoVim whilst in your home dir
2. `:cd some-other-dir` (this is important, opening `init.fnl` before this step will make it work properly afterwards)
3. `e ~/.config/nvim/init.fnl`
4. make some changes and save
5. voilà, it doesn't want to compile

**Comment by udayvir-singh** [comment]
@alexmozaidze I was also able to reproduce that, the issue only appears with `init.fnl`, the rest of the files seem to compile on save.

**Comment by alexmozaidze** [comment]
I dunno, if I remember correctly, it sometimes didn't work with files inside `fnl/` as well. I will try to find a way to reproduce this issue with files in `fnl/`.

**Comment by udayvir-singh** [comment]
@alexmozaidze do you also hard link your config file from another directory, I liked my config files from `~/dotfiles/nvim` directory, when edit file in dotfiles directory then everything works fine but it doesn't work with `~/.config/nvim`.

**Comment by alexmozaidze** [comment]
I have a symlink `~/.config/nvim -> ~/dotfiles/nvim/.config/nvim`.

**Comment by udayvir-singh** [comment]
steps to reproduce:

```
cd any_dir # directory doesn't matter
nvim

---

:e ~/dotfiles/nvim/init.fnl
:w # the hook runs
:bd

:e ~/.config/nvim/init.fnl
:w # the hook doesn't run
```

**Comment by udayvir-singh** [comment]
@alexmozaidze If you still want the hook to run on `~/.config/` then add the following code to your dotfiles:

```lua
local augid = vim.api.nvim_create_augroup("tangerine-onsave-extension", {clear = true})

vim.api.nvim_create_autocmd({"BufWritePost"}, {
	group = augid,
	pattern = {"~/.config/nvim/init.fnl", "~/.config/nvim/fnl/*.fnl"}
	command = "lua require 'tangerine.vim.hooks'.run()",
})
```

or the following fennel code if you use hibiscus:

```fennel
(require-macros :hibiscus.vim)

(augroup! :tangerine-onsave-extension
  [[BufWritePost]
   ["~/.config/nvim/init.fnl" "~/.config/nvim/fnl/*.fnl"]
   "lua require 'tangerine.vim.hooks'.run()"])
```
