### ISSUE TITLE
[Feature Proposal] Separate macros from normal scripts

### ISSUE THREAD

**Issue by alexmozaidze** [udayvir-singh/tangerine.nvim#30]
# Problem

Currently, in order to mark a file as a macro, you are required to suffix it with `-macros.fnl`, which is not ideal.

Normal script files and macro files get mixed up, ending up in a hard-to-read project structure.

# Proposal

Separate normal files and macro files into `fnl/` and `macros/` folders respectively.

Doing so would make it easier to understand which files are to be treated as macros, and which need to be compiled into Lua.

**Comment by udayvir-singh** [comment]
@alexmozaidze After some prototyping and thinking about the proposed solution, I have decided to not a separate `macros/` directory as it is a non-standard solution. However, I have added a new `compiler.adviser` option in tangerine's config, and you can use it to manually add the `macros/` directory in `macro-path` option on fennel compiler:

```lua
tangerine.setup {
  compiler = {
    adviser = function(fennel)
      local dir = vim.fn.stdpath [[config]] .. "/macros"
      local path = string.format(";%s/?.fnl;%s/?/init-macros.fnl", dir, dir)

      fennel["macro-path"] = fennel["macro-path"] .. path

      return fennel
    end,
  }
}
```

**Comment by alexmozaidze** [comment]
Works wonders, thanks! I have to wonder, is there a benefit to returning `fennel` in the function? One might forget to return it, so it would be nice to have the `fennel` be default in case function returns `nil`, a check as such would be nice:
```fnl
(or (config.adviser fennel) fennel)
```
This would make the function more fool-proof.

**Comment by udayvir-singh** [comment]
@alexmozaidze I don't like adding indirection in code, so I would leave it as is. I don't expect normal users to ever touch this feature anyways.
