### ISSUE TITLE
[Bug] De-sync when macros change

### ISSUE THREAD

**Issue by alexmozaidze** [udayvir-singh/tangerine.nvim#32]
# Problem

Whenever a macro file is changed, Tangerine doesn't recompile the entire config, leaving some files that used those (now changed) macros to become outdated.

# Solution

Check if *any* macro file has changed and recompile the entire config.

**Comment by udayvir-singh** [comment]
@alexmozaidze This is not really possible with current architecture of tangerine. You should just use `:FnlCompile!` to force compile all files. the only way to keep track of macro files would be to maintain a dependency graph of every file, which will just turn tangerine into hotpot.
