### ISSUE TITLE
Bug:  In a `custom` chunk, if a dir has a hyphen (-), it won't compile to the right `target` dir

### ISSUE THREAD

**Issue by oblitzitate** [udayvir-singh/tangerine.nvim#35]
Below, for `test_dir`, it will not compile the files to `/lua` but instead to `/fnl`, when it shouldn't. Yet `:FnlGotoOutput` will go to the `/lua` file if it exists, or emit an error message if it doesn't exist.

```fennel
(local tangerine (require :tangerine))

(local awesome_dir (.. (os.getenv "HOME") "/.config/awesome"))
(local test_dir (.. (os.getenv "HOME") "/projects/telescope-test.nvim"))  ; Doesn't work properly
; (local test_dir (.. (os.getenv "HOME") "/projects/telescope_test.nvim")) ; Works properly

(tangerine.setup
  {
   :custom
    [[(.. awesome_dir "/fnl") (.. awesome_dir "/lua")]
     [(.. test_dir "/fnl") (.. test_dir "/lua")]]

   :compiler
    {:globals (vim.list_extend (vim.tbl_keys _G) ["awesome" "screen" "tag" "client" "root" "modkey"])
     :verbose false
     :hooks ["onsave" "oninit"]}})

```

**Comment by udayvir-singh** [comment]
@oblitzitate I have made the commit [585fc8f](https://github.com/udayvir-singh/tangerine.nvim/commit/585fc8f4b8e3acade41bb367bfadf3fa5dd24060), it should fix this issue, try pulling it now.

**Comment by udayvir-singh** [comment]
@oblitzitate Btw, `:FnlGotoOutput` doesn't work for custom paths, and it's by design. You should use it in custom dirs.
