### ISSUE TITLE
How to configure a plugin more.

### ISSUE THREAD

**Issue by horanmustaplot** [udayvir-singh/tangerine.nvim#38]
Hello, I'm new to fennel and this plugin and I wanna configure my plugins more and some of them need dependencies I use lazy and put this in my init.fnl
![image](https://github.com/user-attachments/assets/e4f1fa9c-dbc5-4a13-aea0-58e9489eecb2)

it works but after trying to add extra stuff like this
![image](https://github.com/user-attachments/assets/0a685730-2541-473c-a523-f10183aafa0f)

I'm getting errors when starting neovim
![image](https://github.com/user-attachments/assets/7dc48794-ddea-419b-81be-e6b1ff3fd5e2)

Thanks for the plugin, fennel is kinda better but there's only few repos that uses it so that's why I'm confused using it but would like learning it and use it thx :)

**Comment by udayvir-singh** [comment]
@horanmustaplot no problem, first of all you should read the official fennel docs:

https://fennel-lang.org/tutorial
https://fennel-lang.org/reference

you can also use anti-fennel to compile lua to fennel, this will help you translate lua code example to fennel:

https://fennel-lang.org/see

just type the lua on the right side, and see it translated to fennel.

---

here is an example taken from lazy docs:

```lua
return {
    "hrsh7th/nvim-cmp",
    event = "InsertEnter",
    dependencies = {
      "hrsh7th/cmp-nvim-lsp",
      "hrsh7th/cmp-buffer",
    },
}
```

it can be translated as following:

```fennel
{
  1 "hrsh7th/nvim-cmp"
  :event "InsertEnter"
  :dependencies ["hrsh7th/cmp-nvim-lsp" "hrsh7th/cmp-buffer"]
}
```

---

what you did wrong was using `[]` (an array) instead of `{}` (an table)

**Comment by udayvir-singh** [comment]
also if you want to go deep, you can also start writing macro after you have mastered the basics.

for example, here is the macro for packer.nvim in my [hibiscus.nvim](https://github.com/udayvir-singh/hibiscus.nvim) plugin:

```fennel
(packer!
  (use! :udayvir-singh/hibiscus.nvim)

  (use! :plugin-foo
        :require ["path.mod1" "path.mod2"]) ; automatically requires these modules

  (use! :plugin-baz
        :depends [  ; define dependencies in same syntax as use!
          "example1"
          ["example2" :after "hibiscus.nvim" :require "xyz"]
        ]))
```

**Comment by horanmustaplot** [comment]
> @horanmustaplot no problem, first of all you should read the official fennel docs:
> 
> [fennel-lang.org/tutorial](https://fennel-lang.org/tutorial) [fennel-lang.org/reference](https://fennel-lang.org/reference)
> 
> you can also use anti-fennel to compile lua to fennel, this will help you translate lua code example to fennel:
> 
> [fennel-lang.org/see](https://fennel-lang.org/see)
> 
> just type the lua on the right side, and see it translated to fennel.
> 
> here is an example taken from lazy docs:
> 
> ```lua
> return {
>     "hrsh7th/nvim-cmp",
>     event = "InsertEnter",
>     dependencies = {
>       "hrsh7th/cmp-nvim-lsp",
>       "hrsh7th/cmp-buffer",
>     },
> }
> ```
> 
> it can be translated as following:
> 
> ```fnl
> {
>   1 "hrsh7th/nvim-cmp"
>   :event "InsertEnter"
>   :dependencies ["hrsh7th/cmp-nvim-lsp" "hrsh7th/cmp-buffer"]
> }
> ```
> 
> what you did wrong was using `[]` (an array) instead of `{}` (an table)
> 
> NOTE: in case of mixed array and hashmaps, the indexes (for eg: 1, 2, 3 etc) must be explicitly given

Thanks a lot!!
