### ISSUE TITLE
Why rtpdirs are not compiled on onsave hook?

### ISSUE THREAD

**Issue by vinibispo** [udayvir-singh/tangerine.nvim#5]
I was reading documentation and one part caught my attention.
```lua
            -- hooks for tangerine to compile on:
            -- "onsave" run every time you save fennel file in {source} dir.
            -- "onload" run on VimEnter event
            -- "oninit" run before sourcing init.fnl [recommended than onload]
```
I was trying to compile "rtpdirs" on "onsave hook", but I have not found a way, how can I get this result?

**Comment by udayvir-singh** [comment]
fixed with [#73cdc3f](https://github.com/udayvir-singh/tangerine.nvim/commit/73cdc3f24b57b72fc1605e768c5bdb859d36954a)
