### ISSUE TITLE
Mappings working on `non-fennel` files

### ISSUE THREAD

**Issue by vinibispo** [udayvir-singh/tangerine.nvim#6]
I was trying `g` commands on neovim, and I realized that when I'm on a non-fennel file, the tangerine mappings are still enabled, which is terrible.
Could we set shortcuts only in fennel files?

**Comment by udayvir-singh** [comment]
@vinibispo

The mappings were made global because sometimes you want to evaluate fennel code in other files like markdown or org-mode. But if you want them to only map in fennel files
