### ISSUE TITLE
Allow to split an rtpdir into source and target

### ISSUE THREAD

**Issue by oblitzitate** [udayvir-singh/tangerine.nvim#7]
Would be nice to have separated `/fnl` and `/lua` folders in rtpdirs also.

**Comment by udayvir-singh** [comment]
@oblitzitate

You can use `tangerine.api.compile.dir` to achieve that:
```lua
require [[tangerine]].setup {...}

local nvim_dir = vim.fn.stdpath [[config]]

_G.tangerine.api.compile.dir(
  nvim_dir .. "/rtpdir/fnl",
  nvim_dir .. "/rtpdir/lua"
)
```

See `:help tangerine.api.compile.dir()` for more info.
