### ISSUE TITLE
Allow to peak at a specific node (instead of range)

### ISSUE THREAD

**Issue by oblitzitate** [udayvir-singh/tangerine.nvim#8]
I noticed that `FnlPeak` targets a range but it'd be nice to target a specific node also. I feel like that's the more sensible way to do Fennel peaks.

Got the idea from [Olical/conjure](https://github.com/Olical/conjure) where you can evaluate a specific node (e.g. word node, current node, root node, etc.).

**Comment by udayvir-singh** [comment]
@oblitzitate 

I am currently taking a break from this project. So I would add this feature when I get some free time and some refactoring has been done to current codebase.

**Comment by oblitzitate** [comment]
Alright cool! Also I just realized, I think it should probably be `Peek` (taking a glance) instead of `Peak` (top/pinnacle of something)

**Comment by udayvir-singh** [comment]
@ob

**Comment by udayvir-singh** [comment]
@oblitzitate 

Thanks for finding out that silly typo. I could fix that now but it can cause some breaking changes, so I will fix it when I am releasing a newer version.

**Comment by udayvir-singh** [comment]
@oblitzitate

After thinking for some time I have decided to close this issue as adding this feature requires a lot of refactoring in current codebase.
